config/routes.rb
Jualo::Application.routes.draw do

  resources :spam_reports

  resources :abuse_reports

  resources :attach_tokens

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :currencies

  resources :ads_variants

  resources :variants

  resources :options

  resources :options_variants

  resources :category_options

  resources :ad_types
  match "ads/send_email" => "ads#send_email", :as => :send_email

  resources :static_pages

   match "users/register" => "users#register"
  resources :users

  resources :states do
      resources :cities do
          resources :categories  do
          end
      end
  end

 match '/(:state)(/:city)(/:category)(/:id)/get_new_captcha' => 'ads#get_new_captcha', :as => :ad_new_captcha

  match '/(:state)(/:city)(/:category)(/:id)/verify_name' => 'ads#verify_name', :as => :ad_verify_name
  match '/(:state)(/:city)(/:category)(/:id)/verify_email' => 'ads#verify_email', :as => :ad_verify_email
  match '/(:state)(/:city)(/:category)(/:id)/verify_phone_number' => 'ads#verify_phone_number', :as => :ad_verify_phone_number
  match '/(:state)(/:city)(/:category)(/:id)/verify_subject' => 'ads#verify_subject', :as => :ad_verify_subject
  match '/(:state)(/:city)(/:category)(/:id)/verify_message' => 'ads#verify_message', :as => :ad_verify_message
  match '/(:state)(/:city)(/:category)(/:id)/verify_captcha' => 'ads#verify_captcha', :as => :ad_verify_captcha
  match '/(:state)(/:city)(/:category)(/:id)/verify_for_emptiness' => 'ads#verify_for_emptiness', :as => :ad_verify_for_emptiness

  resources :ads

 resources :categories

  resources :images

  resources :details

 match "export_categories" => "categories#export_categories"
 match "export_products" => "categories#export_products"

   root :to => 'categories#home'

devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#match '/ad/new' => 'ads#new', :as => :new_ad

  match '/(:state)(/:city)(/:category)(/:id)/' => 'ads#show', :as => :ad

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :remember_me,:provider, :uid,:name, :phone, :blackberry_pin
	has_many :ads

	def self.new_with_session(params, session)
		super.tap do |user|
			if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
		end
	end

	def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
		user = User.where(:provider => auth.provider, :uid => auth.uid).first
		unless user

			user_exist = User.where('email = ?', auth.info.email).first #check if user exists
			if user_exist
				user_exist.update_attributes(:provider => auth.provider, :uid => auth.uid)
				user_exist.save
				return user_exist

			else
				user = User.create(name:auth.extra.raw_info.name,
				provider:auth.provider,
				uid:auth.uid,
				email:auth.info.email,
				password:Devise.friendly_token[0,20]
				)
			end


		end
		user
	end


end

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		# You need to implement the method below in your model (e.g. app/models/user.rb)
		@user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
			set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json

  def register
    unless session[:user]
      redirect_to root_path and return false
    end

    @user = User.new(session[:user])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/register.html.erb
<h2>Please register before to continue</h2>
 
<% resource_name = "user" %>
Before you will be able to post ads you need to log register.
<br>
 <%= link_to "<h3>Sign in with Facebook</h3>".html_safe, user_omniauth_authorize_path(:facebook) %>
<p>
 or make an account:

 <p>

<%= form_for @user,:url => registration_path(@user) do |f| %>

  <div><%= f.label :password %><br />
  <%= f.password_field :password, :autofocus => true  %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Sign up" %></div>
<% end %>


app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @user.phone %></dd>
</dl>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:ad_type_id) %></th>

      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:main_image_id) %></th>
      <th><%= model_class.human_attribute_name(:city_id) %></th>
      <th><%= model_class.human_attribute_name(:state_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% current_user.ads.each do |ad| %>
      <tr>
        <td><%= link_to ad.detail.try(:name), ad_path(ad) %></td>
        <td><%= ad.category.name %></td>
        <td><%= ad.ad_type.name %></td>
        <td><%= ad.price %></td>
        <td><%= image_tag(ad.image.image.url(:thumb)) if ad.image %></td>
        <td><%= ad.city.name %></td>
        <td><%= ad.state.name %></td>
        <td><%=l ad.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ad_path(ad), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ad_path(ad),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>