config/routes.rb
Jualo::Application.routes.draw do

  resources :spam_reports

  resources :abuse_reports

  resources :attach_tokens

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :currencies

  resources :ads_variants

  resources :variants

  resources :options

  resources :options_variants

  resources :category_options

  resources :ad_types
  match "ads/send_email" => "ads#send_email", :as => :send_email

  resources :static_pages

   match "users/register" => "users#register"
  resources :users

  resources :states do
      resources :cities do
          resources :categories  do
          end
      end
  end

 match '/(:state)(/:city)(/:category)(/:id)/get_new_captcha' => 'ads#get_new_captcha', :as => :ad_new_captcha

  match '/(:state)(/:city)(/:category)(/:id)/verify_name' => 'ads#verify_name', :as => :ad_verify_name
  match '/(:state)(/:city)(/:category)(/:id)/verify_email' => 'ads#verify_email', :as => :ad_verify_email
  match '/(:state)(/:city)(/:category)(/:id)/verify_phone_number' => 'ads#verify_phone_number', :as => :ad_verify_phone_number
  match '/(:state)(/:city)(/:category)(/:id)/verify_subject' => 'ads#verify_subject', :as => :ad_verify_subject
  match '/(:state)(/:city)(/:category)(/:id)/verify_message' => 'ads#verify_message', :as => :ad_verify_message
  match '/(:state)(/:city)(/:category)(/:id)/verify_captcha' => 'ads#verify_captcha', :as => :ad_verify_captcha
  match '/(:state)(/:city)(/:category)(/:id)/verify_for_emptiness' => 'ads#verify_for_emptiness', :as => :ad_verify_for_emptiness

  resources :ads

 resources :categories

  resources :images

  resources :details

 match "export_categories" => "categories#export_categories"
 match "export_products" => "categories#export_products"

   root :to => 'categories#home'

devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#match '/ad/new' => 'ads#new', :as => :new_ad

  match '/(:state)(/:city)(/:category)(/:id)/' => 'ads#show', :as => :ad

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent, :id
  has_many :ads
  has_many :options

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json

  def export_categories
    @response = ActiveSupport::JSON.decode(params[:data])
    @response.each{|catalog|
      if Category.where("id = ?", catalog["id"]).size == 0
        Category.new(:id => catalog["id"], :parent => catalog["parent"], :name => catalog["name"]).save
      else
       @cat =  Category.find(catalog["id"])
       @cat.update_attributes(:parent => catalog["parent"], :name => catalog["name"])
        @cat.save
      end

    }
  end

  def export_products
    @response = ActiveSupport::JSON.decode(params[:data])
#(id SERIAL, name VARCHAR(255), short_des VARCHAR(500) , des TEXT, images TEXT, category_id INT, address VARCHAR(5000), phone VARCHAR(255), price VARCHAR(255) , used TINYINT, username VARCHAR(255), exported TINYINT, PRIMARY KEY (id))")
    @response.each{|ad|

      @user = User.where("name = ?", ad["username"])
      if @user.size == 0
        @user = User.new(:name => ad["username"], :phone => ad["phone"])
        @user.save(:validate => false)
      else
        @user = @user.first
      end

      address = ad["address"].split(/,/)

      sate_name =  address[1].strip
      city_name =  address[0].strip

      @state = State.where("name = ?", sate_name)
      if State.where("name = ?", sate_name).size == 0
        @state = State.new(:name => sate_name)
        @state.save(:validate => false)
      else
        @state = @state.first
      end

      @city = City.where("name = ?", city_name)
      if @city.size == 0
        @city = City.new(:name => city_name, :state_id => @state.id)
        @city.save(:validate => false)
      else
       @city =  @city.first
      end

      @ad = Ad.where("id = ?", ad["id"])
      if @ad.size == 0
        @ad = Ad.new(:id => ad["id"],
  :category_id => ad["category_id"],
  :ad_type_id => 0,
  :ad_condition_id => 0 ,
  :price => ad["price"],
  :image_id => nil )
        @ad.city = @city
        @ad.state = @state
        @ad.user = @user
        @ad.save(:validate => false)


      @details = Detail.new(:name => ad["name"], :ad_id => @ad.id, :description => ad["des"])
      @details.save(:validate => false)

    ad["images"].split(/,/).each{|img|

      @image = Image.new(:title => ad['name'], :ad_id => @ad.id, :url => img, :need_download => true)
      @image.save(:validate => false)
      if @ad.image_id == nil
        @ad.image_id = @image.id
        @ad.save(:validate => false)
      end
    }

      end



    }

  end


  def home

    @states = State.all

    @new = Ad.where('image_id > 1').order("created_at DESC").limit(7)
    @hot = Ad.where('image_id > 1').order("created_at ASC").limit(7)

    @categories = Category.where('parent = 1')

    @ads_count = Ad.all.count

  end

  def index
    redirect_to root_path and return true
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json



  def show


    @category = Category.where('parent > 0').limit(1).first #.find(params[:id])
    @catalogs = Category.where("parent = ?", @category.id)
    begin
    @parent_cat = Category.find(@category.parent)
    rescue
     @parent_cat = Category.find(1)
    end


    if params[:filter]
      filters = ""
      params[:filter].each do |filter|
        filters += " AND " if filters != ""
        filters += " id IN (SELECT ad_id AS id FROM ads_variants WHERE variant_id = #{filter[1]})"
     end
      @ads = @category.ads.where(filters).order('created_at DESC').paginate(:page => params[:page], :per_page => params[:per_page])
   else
      @ads = @category.ads.order('created_at DESC').paginate(:page => params[:page], :per_page => params[:per_page])
    end
@ad_type = nil
case params[:ad_type]
when "new"
  @ad_type = 1
when "second"
@ad_type = 2
when "searched"
  @ad_type = 3
end

@view = nil
case params[:view]
when "grid"
@view = "grid"
else
@view = "table"
end



    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end

  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent %><br />
    <%= f.number_field :parent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_grid_view.html.erb
  
   <ol class="list grid-list clearfix">

<% ads.each do |ad| %>
    <li>
      <div class="list-inner clearfix ">
        <div class="time_left_block"><%=time_ago_in_words(ad.created_at) %></div>
        <div class="product-description-left-block">
          <div class="product-img">
            <div class='sqr_image_block nohover'>
              <% if ad.image %>
            <%= link_to image_tag(ad.image.image(:thumb), :class => 'sqr_image ', :size => "90x90", :alt=> "[Image: Villa Samudra Raya]", :title => "Villa Samudra Raya"), ad_path(ad.state, ad.city, ad.category, ad) %>
            <% end %>
            </div>
          </div>
        </div>
        <div class="product-description-right-block grid_5 omega alpha">
          <h3><%= link_to "<span class='c'>#{truncate(ad.name,:length => 35)}</span>".html_safe, ad_path(ad.state, ad.city, ad.category, ad) %></h3>
          <div class="clearfix other-items-outer">
            <ul class="item-location-block clearfix">
              <li class="item-loc"><span class="c"><%= truncate( "#{ad.city.name} , #{ad.state.name}",:length => 17) %> </span></li>
              <li class="item-type"><%= ad.ad_type.name %></li>
            </ul>
          </div>
        </div>
        <p class="item-amount-block"><span class="c cr" title="zero dollars">Rp<%= ad.price.to_i %></span></p>
        <div class="item-sold-block clearfix"></div>
      </div>
    </li>
   <% end %>
 </ol>

app/views/categories/_map.html.erb
<div class="map-container clearfix">
  <span class="map-side-img">image</span>
  <div id="area_image" class="map sprite_index_map_map_s1c_blue">
    <img src="/assets/transparent_bootstrap_1px.gif" alt_disable="Indonesia map" id="area_highlight" />
    <img src="/assets/transparent_bootstrap_1px.gif" alt_disable="Indonesia map" id="area_map" usemap="#indonesia_map" />
    <map name="indonesia_map">
      <area shape="poly" onMouseOver="change_image(0,1)"
            onMouseOut="override_hide_image(0,1)"
            onClick="return startpage_set_default_ca('0', '.berniaga.com');"
            alt_disable="Seluruh Indonesia" title="Seluruh Indonesia" coords="0,0,0,0,0,0"
            href="#" xtclib="index_INDONESIA_img">
      <area shape="poly" onMouseOver="change_image(1,1)"
            onMouseOut="override_hide_image(1,1)"  alt_disable="BALI: Denpasar,
            Singaraja, Kuta, Ubud, Sanur, Nusa Dua"
            coords="369,275,371,267,367,262,371,258,382,253,388,241,387,229,379,216,366,211,354,212,342,224,339,235,342,246,350,254,356,262,349,262,349,265,358,270"
            href="products/pv:11" xtclib="index_BALI_img">
      <area shape="poly" onMouseOver="change_image(2,1)"
            onMouseOut="override_hide_image(2,1)"  alt_disable="BANTEN: Tangerang,
            Serang, Cilegon, Anyer, Carita, Pandeglang, Rangkasbitung"
            coords="179,238,184,235,191,232,192,227,196,221,205,223,205,229,210,234,209,239,206,242,195,239,187,241"
            href="products/pv:7" xtclib="index_BANTEN_img">
      <area shape="poly" onMouseOver="change_image(3,1)"
            onMouseOut="override_hide_image(3,1)"  alt_disable="BENGKULU:
            Bengkulu"
            coords="106,164,114,159,121,164,126,170,133,175,139,178,141,182,138,187,143,192,150,197,155,201,154,207,131,215,126,210,131,206,137,198,133,189,127,183,119,178"
            href="products/pv:15" xtclib="index_BENGKULU_img">
      <area shape="poly" onMouseOver="change_image(4,1)"
            onMouseOut="override_hide_image(4,1)"  alt_disable="DIY: Yogyakarta"
            coords="269,257,274,252,284,257,284,265,269,259"
            href="products/pv:8" xtclib="index_DIY_img">
      <area shape="poly" onMouseOver="change_image(5,1)"
            onMouseOut="override_hide_image(5,1)"  alt_disable="DKI: Jakarta"
            coords="206,222,206,230,210,233,216,231,218,227,217,223,214,221,206,221,206,221"
            href="products/pv:49" xtclib="index_DKI_img">
      <area shape="poly" onMouseOver="change_image(6,1)"
            onMouseOut="override_hide_image(6,1)"  alt_disable="JAMBI: Jambi"
            coords="115,158,126,167,136,162,142,157,148,159,153,151,158,149,165,148,170,146,168,137,163,132,151,132,146,130,135,135,124,134,120,138,115,149"
            href="products/pv:18" xtclib="index_JAMBI_img">
      <area shape="poly" onMouseOver="change_image(7,1)"
            onMouseOut="override_hide_image(7,1)"  alt_disable="JABAR: Bandung,
            Bogor, Garut, Tasikmalaya, Bekasi, Cimahi, Cirebon, Depok, Sukabumi"
            coords="204,248,212,248,217,250,232,256,242,257,246,253,243,246,247,242,248,239,245,235,237,229,227,228,222,224,214,221,214,228,214,233,209,234"
            href="products/pv:4" xtclib="index_JABAR_img">
      <area shape="poly" onMouseOver="change_image(8,1)"
            onMouseOut="override_hide_image(8,1)"  alt_disable="JATENG: Semarang,
            Magelang, Surakarta, Salatiga, Pekalongan, Tegal"
            coords="250,235,246,243,242,244,243,249,246,251,248,254,258,254,270,258,274,251,284,256,284,263,287,264,288,260,293,257,291,246,297,247,299,245,301,234,291,235,288,230,282,230,278,238,268,238,261,236,259,237,253,236"
            href="products/pv:6" xtclib="index_JATENG_img">
      <area shape="poly" onMouseOver="change_image(9,1)"
            onMouseOut="override_hide_image(9,1)"  alt_disable="JATIM: Surabaya,
            Batu, Blitar, Kediri, Madiun, Malang, Mojokerto, Pasuruan, Probolinggo,
            Surabaya"
            coords="298,236,306,239,314,240,318,244,320,240,330,239,334,239,343,240,340,243,331,246,325,245,320,245,319,253,324,254,331,255,343,254,350,258,348,266,352,274,343,271,336,270,328,265,315,267,307,268,299,269,293,267,288,264,292,257,291,250"
            href="products/pv:5" xtclib="index_JATIM_img">
      <area shape="poly" onMouseOver="change_image(10,1)"
            onMouseOut="override_hide_image(10,1)"  alt_disable="KALBAR:
            Pontianak, Singkawang, Ketapang, KALTENG: Palangkaraya, Sampit, KALSEL:
            Banjarmasin, Banjarbaru, KALTIM: Samarinda, Tarakan, Balikpapan,
            Bontang, Nunukan"
            coords="278,173,266,168,267,153,259,141,251,128,247,110,248,92,261,81,274,96,292,100,305,95,319,87,327,94,343,92,349,87,358,73,364,61,369,44,379,40,400,41,409,49,408,56,412,71,418,83,429,98,416,108,404,115,406,126,403,136,392,145,386,157,388,165,384,183,381,191,360,191,344,193,348,182,324,178,313,183,299,183,295,172"
            href="products/pv:22"
            xtclib="index_KALBAR_KALTENG_KALSEL_KALTIM_img">
      <area shape="poly" onMouseOver="change_image(11,1)"
            onMouseOut="override_hide_image(11,1)"
            alt_disable="LAMPUNG: Bandar Lampung, Metro"
            coords="156,207,162,205,167,199,171,194,178,192,183,187,191,189,196,211,193,220,187,219,184,215,181,221,175,218,173,221,166,220"
            href="products/pv:27" xtclib="index_LAMPUNG_img">
      <area shape="poly" onMouseOver="change_image(12,1)"
            onMouseOut="override_hide_image(12,1)" alt_disable="NAD: Banda Aceh,
            Langsa, Lhokseumawe, Sabang"
            coords="1,8,5,12,12,17,21,20,31,22,42,21,48,27,50,35,51,42,52,47,49,52,52,57,52,63,53,70,53,77,48,77,42,80,35,82,26,79,17,73,9,69,15,56,20,49,14,40,6,32,1,22,1,12"
            href="products/pv:12"
            xtclib="index_NAD_img">
      <area shape="poly" onMouseOver="change_image(13,1)"
            onMouseOut="override_hide_image(13,1)"
            alt_disable="NTB: Matarman, Bima, Kepulauan Gili, Kuta Lombok, NTT: Kupang"
            coords="612,264,604,242,578,248,535,258,511,261,494,260,491,265,480,266,471,266,447,261,434,260,417,260,397,264,390,264,379,263,374,269,374,273,375,276,384,279,391,282,407,281,419,280,423,285,430,293,440,295,448,301,459,305,471,309,480,312,511,312,536,295,543,284,567,271"
            href="products/pv:30,31" xtclib="index_NTB_NTT_img">
      <area shape="poly" onMouseOver="change_image(14,1)"
            onMouseOut="override_hide_image(14,1)"  alt_disable="MALUT: Ternate,
            Tidore, Jailolo, AMBON: Ambon, Dobo, Namlea, PAPARAT: Fak-Fak, Sorong,
            Manokwari, Bintuni, Kaimana, PAPUA: Jayapura, Merauke, Biak, Timika,
            Nabire, Agats, Serui"
            coords="618,258,624,263,642,267,651,262,659,253,662,242,682,225,699,228,700,241,710,244,717,232,736,202,746,207,766,218,773,230,777,242,768,249,760,268,764,274,774,270,782,270,788,265,795,268,806,264,824,282,827,277,825,161,819,155,807,155,795,151,780,145,773,141,764,140,751,142,744,134,735,126,726,126,719,130,710,130,703,125,692,126,682,124,670,120,660,122,653,117,641,113,630,114,615,108,605,95,605,70,597,69,580,90,581,112,577,126,577,143,529,144,522,152,544,156,551,167,552,176,565,191,581,187,595,183,616,183,631,190,644,196,654,209,662,219,660,231,652,242,642,253,623,252"
            href="products/pv:28,29"
            xtclib="index_MALUT_AMBON_PAPARAT_PAPUA_img">
      <area shape="poly" onMouseOver="change_image(15,1)"
            onMouseOut="override_hide_image(15,1)"
            alt_disable="RIAU: Dumai, Pakanbaru, KEPRI: Batam, Tanjung Pinang"
            coords="91,68,97,74,103,77,109,76,113,80,119,79,160,67,166,63,191,63,193,60,200,57,233,46,237,43,239,47,241,52,223,53,204,59,202,63,193,66,167,69,154,72,124,83,137,89,147,97,162,100,180,120,172,124,159,124,151,127,143,131,134,136,129,133,120,134,107,127,100,112,94,108,91,102,93,93,98,89,98,81"
            href="products/pv:35"
            xtclib="index_RIAU_img">
      <area shape="poly" onMouseOver="change_image(16,1)"
            onMouseOut="override_hide_image(16,1)"
            alt_disable="SULBAR: Polewali, Majene, Mamuju, SULSEL: Makassar, Pare-Pare, Tana
            Toraja, Palopo, SULTENGG: Kendari, Wakatobi, Bau Bau"
            coords="469,250,468,242,461,229,462,216,470,208,482,214,495,221,502,218,513,213,516,206,507,195,510,187,498,185,490,175,486,173,479,167,475,161,470,159,461,159,455,151,446,151,445,146,440,138,440,134,434,140,432,148,432,153,432,159,430,162,426,166,427,181,435,181,440,186,440,194,438,203,435,210,436,217,450,221,455,217,453,226,455,233,457,241,457,248"
            href="products/pv:10"
            xtclib="index_SULBAR_SULSEL_SULTENGG_img">
      <area shape="poly" onMouseOver="change_image(17,1)"
            onMouseOut="override_hide_image(17,1)"
            alt_disable="SULUT: Manado, Bitung, Tondano, GORONTALO: Gorontalo, SULTENG:
            Palu, Toli-Toli, Poso, Donggala, Buol"
            coords="442,131,442,119,445,110,449,99,459,96,476,94,488,98,499,98,520,97,529,91,541,83,542,69,541,53,546,46,552,43,567,35,573,36,574,43,573,50,565,59,552,66,549,80,546,85,545,86,542,97,531,110,507,124,511,133,518,145,518,152,498,151,486,145,483,149,482,160,493,173,481,168,470,157,463,157,454,153,447,147,440,139"
            href="products/pv:40"
            xtclib="index_SULUT_GORONTALO_SULTENG_img">
      <area shape="poly" onMouseOver="change_image(18,1)"
            onMouseOut="override_hide_image(18,1)"
            alt_disable="SUMBAR: Padang, Bukittinggi, Padang Panjang, Pariaman, Payakumbuh,
            Sawahlunto, Solok"
            coords="98,171,102,165,108,160,113,158,113,154,115,147,118,141,120,135,114,130,107,126,105,121,104,115,101,110,94,108,91,103,85,103,85,107,83,108,77,108,74,114,78,122,77,129,67,130,63,136,63,144,72,151,77,152,80,160,86,161,87,168,90,171,95,174"
            href="products/pv:41" xtclib="index_SUMBAR_img">
      <area shape="poly" onMouseOver="change_image(19,1)"
            onMouseOut="override_hide_image(19,1)"  alt_disable="SUMSEL:
            Palembang, Prabumulih, Lahat, Baturaja, BABEL: Pangkal Pinang"
            coords="127,169,132,173,136,176,140,177,142,180,138,185,139,189,146,194,153,196,155,203,160,205,164,201,169,193,177,192,183,186,188,187,197,182,202,173,210,172,225,173,233,177,238,169,234,163,226,160,210,161,206,159,198,154,200,150,194,143,188,143,180,151,173,152,169,147,160,148,154,152,151,158,144,158"
            href="products/pv:42"
            xtclib="index_SUMSEL_BABEL_img">
      <area shape="poly" onMouseOver="change_image(20,1)"
            onMouseOut="override_hide_image(20,1)"
            alt_disable="SUMUT: Medan, Binjai, Padang Sidempuan, Pematangsiantar, Sibolga,
            Tanjung Balai, Tebing Tinggi"
            coords="59,40,53,43,50,52,55,61,53,78,37,92,36,93,48,109,53,106,53,94,42,88,53,77,66,86,74,110,60,114,56,116,62,126,66,122,62,112,75,112,81,107,87,109,89,106,86,101,93,103,93,94,90,91,100,89,99,87,92,79,97,83,97,71,97,69,84,57,70,49,61,41,59,40,59,41"
            href="products/pv:9" xtclib="index_SUMUT_img">
      <area shape="poly" coords="783,265" href="#">
    </map>
    <div class="fb_home">
      <div class="fb-like" data-href="https://www.facebook.com/jualocom" data-send="true" data-layout="button_count" data-width="450" data-show-faces="true" data-font="lucida grande"></div>
    </div>
  </div>
</div>
<!-- Map Area -->
<!-- Map Area end -->

app/views/categories/_table_view.html.erb

  <ol class="list add-list clearfix">
    <% ads.each do |ad| %>
    <li>
      <div class="list-inner clearfix ">
        <div class="time_left_block hidden-phone"><%= time_ago_in_words(ad.created_at) %></div>
        <div class="product-description-left-block">
          <div class="product-img">
          	<div class='sqr_image_block nohover'>
              <% if ad.image %>
          	<%= link_to image_tag(ad.image.image(:thumb), :class => 'sqr_image ', :size => "90x90", :alt=> "[Image: Villa Samudra Raya]", :title => "Villa Samudra Raya"), ad_path(ad.state, ad.city, ad.category, ad) %>
            <% end %>
            </div>
          </div>
        </div>
        <div class="product-description-right-block grid_5 omega alpha">
          <h3><%= link_to "<span class='c'>#{ad.name}</span>".html_safe, ad_path(ad.state, ad.city, ad.category, ad) %></h3>
          <div class="clearfix other-items-outer">
            <ul class="item-location-block clearfix">
              <li class="item-loc"><span class="c"><%= ad.city.try(:name) %>, <%= ad.state.try(:name) %> </span></li>
              <li class="item-type"><%= ad.ad_type.try(:name) %></li>
            </ul>
          </div>
        <div class="visible-phone clearfix mobile_date">
          <%=time_ago_in_words(ad.created_at) %> ago
        </div>
        </div>
        <p class="item-amount-block"><span class="c cr" title="zero dollars">Rp<%= ad.price.to_i %></span></p>
        <div class="item-sold-block clearfix"></div>
      </div>
    </li>
   <% end %>
 </ol>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/home2.html.erb

<div class='mainpage_city_banner'>
	<center>
<h4>Start Selling the products within 60 seconds</h4>
<div class="btn-group">
 <%= link_to '<button class="btn btn-large btn-primary ">Start Selling</button>'.html_safe , new_ad_path() %>
<button class="btn btn-large btn-primary  dropdown-toggle">
<span class="caret"></span>
</button>
</center>
</div>
</div>
</div>
<p></p>
<br><br>

<div class='row-fluid'>

	<div class='span12'>
<div class='image_bar'>
	<div class='image_block'>
1 minute ago 
</div>
<% @new.each do |ad| %>
<div class='image_block'>
<table width="100%" height="100%" align="center" valign="center">
   <tr><td><center class='nohover'>
<%= link_to image_tag(ad.image.image.url(:thumb)), ad_path(ad.state,ad.city,ad.category,ad) %></center>
 </td></tr>
   </table>
</div>
<% end %>

</div>
</div></div>


<br><br>
<h4>Choose a Location</h4>
<% @states.each do |state| %>
<%= link_to state.name, state_path(state) %>
<% end %>

<br><br>
<h4>Choose category</h4>
<% @categories.each do |category| %>
<%= link_to category.name, category_path(category) %>
<% end %>


app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Parent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.parent %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>