config/routes.rb
Jualo::Application.routes.draw do

  resources :spam_reports

  resources :abuse_reports

  resources :attach_tokens

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :currencies

  resources :ads_variants

  resources :variants

  resources :options

  resources :options_variants

  resources :category_options

  resources :ad_types
  match "ads/send_email" => "ads#send_email", :as => :send_email

  resources :static_pages

   match "users/register" => "users#register"
  resources :users

  resources :states do
      resources :cities do
          resources :categories  do
          end
      end
  end

 match '/(:state)(/:city)(/:category)(/:id)/get_new_captcha' => 'ads#get_new_captcha', :as => :ad_new_captcha

  match '/(:state)(/:city)(/:category)(/:id)/verify_name' => 'ads#verify_name', :as => :ad_verify_name
  match '/(:state)(/:city)(/:category)(/:id)/verify_email' => 'ads#verify_email', :as => :ad_verify_email
  match '/(:state)(/:city)(/:category)(/:id)/verify_phone_number' => 'ads#verify_phone_number', :as => :ad_verify_phone_number
  match '/(:state)(/:city)(/:category)(/:id)/verify_subject' => 'ads#verify_subject', :as => :ad_verify_subject
  match '/(:state)(/:city)(/:category)(/:id)/verify_message' => 'ads#verify_message', :as => :ad_verify_message
  match '/(:state)(/:city)(/:category)(/:id)/verify_captcha' => 'ads#verify_captcha', :as => :ad_verify_captcha
  match '/(:state)(/:city)(/:category)(/:id)/verify_for_emptiness' => 'ads#verify_for_emptiness', :as => :ad_verify_for_emptiness

  resources :ads

 resources :categories

  resources :images

  resources :details

 match "export_categories" => "categories#export_categories"
 match "export_products" => "categories#export_products"

   root :to => 'categories#home'

devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#match '/ad/new' => 'ads#new', :as => :new_ad

  match '/(:state)(/:city)(/:category)(/:id)/' => 'ads#show', :as => :ad

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  attr_accessible :ad_id, :address, :description, :name
  belongs_to :ad
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  # GET /details
  # GET /details.json
  def index
    @details = Detail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @details }
    end
  end

  # GET /details/1
  # GET /details/1.json
  def show
    @detail = Detail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @detail }
    end
  end

  # GET /details/new
  # GET /details/new.json
  def new
    @detail = Detail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @detail }
    end
  end

  # GET /details/1/edit
  def edit
    @detail = Detail.find(params[:id])
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(params[:detail])

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render json: @detail, status: :created, location: @detail }
      else
        format.html { render action: "new" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /details/1
  # PUT /details/1.json
  def update
    @detail = Detail.find(params[:id])

    respond_to do |format|
      if @detail.update_attributes(params[:detail])
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail = Detail.find(params[:id])
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= form_for @detail, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :ad_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :ad_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                details_path, :class => 'btn' %>
  </div>
<% end %>

app/views/details/edit.html.erb
<%- model_class = Detail -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/details/index.html.erb
<%- model_class = Detail -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:ad_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= link_to detail.id, detail_path(detail) %></td>
        <td><%= detail.ad_id %></td>
        <td><%= detail.name %></td>
        <td><%= detail.description %></td>
        <td><%= detail.address %></td>
        <td><%=l detail.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_detail_path(detail), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      detail_path(detail),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_detail_path,
            :class => 'btn btn-primary' %>

app/views/details/new.html.erb
<%- model_class = Detail -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/details/show.html.erb
<%- model_class = Detail -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ad_id) %>:</strong></dt>
  <dd><%= @detail.ad_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @detail.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @detail.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @detail.address %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              details_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_detail_path(@detail), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              detail_path(@detail),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>